# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/semisupervised_learning',
                'doc_host': 'https://HasanGoni.github.io',
                'git_url': 'https://github.com/HasanGoni/semisupervised_learning',
                'lib_path': 'semisupervised_learning'},
  'syms': {'semisupervised_learning.core': {'semisupervised_learning.core.foo': ('core.html#foo', 'semisupervised_learning/core.py')}}}
