"""Fill in a module description here"""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/00_core.ipynb.

# %% auto 0
__all__ = ['foo', 'MultiCropDataset']

# %% ../nbs/00_core.ipynb 4
def foo(): pass

# %% ../nbs/00_core.ipynb 6
from cv_tools.imports import *
from cv_tools.core import *

# %% ../nbs/00_core.ipynb 7
from fastcore.all import *
import matplotlib.pyplot as plt

# %% ../nbs/00_core.ipynb 8
# torch related imports
import torch
from torchvision import transforms
import numpy as np

# %% ../nbs/00_core.ipynb 14
class MultiCropDataset(torch.utils.data.Dataset):
    __repr_attrs__ = ['ds', 'image_column', 'n_global', 'n_local']
    def __init__(
        self,
        ds,
        image_column='image',
        n_global=2,
        n_local=8,
        global_crop=None,
        local_crop=None,
    ):
        store_attr()
        if global_crop is None:
            self.global_crop = transforms.Compose([
                transforms.RandomResizedCrop(224),
                transforms.RandomHorizontalFlip(),
                transforms.ToTensor(),
                transforms.Normalize(mean=[0.485, 0.456, 0.406], std=[0.229, 0.224, 0.225])
            ])
        if local_crop is None:
            self.local_crop = transforms.Compose([
                transforms.RandomResizedCrop(96, scale=(0.05, 0.4)),
                transforms.RandomHorizontalFlip(),
                transforms.ToTensor(),
                transforms.Normalize(mean=[0.485, 0.456, 0.406], std=[0.229, 0.224, 0.225])
            ])
    
    # Optional: define a custom repr
    def __repr__(self):
        return f"MultiCropDataset(ds={self.ds}, image_column={self.image_column}, n_global={self.n_global}, n_local={self.n_local})"

    def __getitem__(self, idx):
        img = self.ds[idx][self.image_column]
        if isinstance(img, dict):
            img = img['image'] if 'image' in img else img
        if not hasattr(img, 'convert'):
            img = transforms.ToPILImage()(img) if torch.is_tensor(img) else img
        img = img.convert('RGB') if hasattr(img, 'convert') else img
        crops = []
        crops = [self.global_crop(img) for _ in range(self.n_global)]
        crops += [self.local_crop(img) for _ in range(self.n_local)]
        return crops

    def __len__(self):
        return len(self.ds)
   

# %% ../nbs/00_core.ipynb 15
@patch_to(MultiCropDataset)
def _denormalize(self, tensor):
    """Denormalize tensor for display"""
    mean = torch.tensor([0.485, 0.456, 0.406]).view(3, 1, 1)
    std = torch.tensor([0.229, 0.224, 0.225]).view(3, 1, 1)
    return tensor * std + mean


# %% ../nbs/00_core.ipynb 17
@patch_to(MultiCropDataset)
def show_ds(self, n=4, scale=1):
    """Show n samples from the dataset with all their crops"""
    n = min(n, len(self.ds))
    n_crops = self.n_global + self.n_local
        
    # Create figure with proper layout
    fig, axs = plt.subplots(n, n_crops, figsize=(n_crops * 2 * scale, n * 2 * scale))
    if n == 1:
        axs = axs.reshape(1, -1)
        
    for i in range(n):
        # Get image and generate crops
        img = self.ds[i][self.image_column]
        if isinstance(img, dict):
            img = img['image'] if 'image' in img else img
        if not hasattr(img, 'convert'):
            img = transforms.ToPILImage()(img) if torch.is_tensor(img) else img
        img = img.convert('RGB') if hasattr(img, 'convert') else img
            
        # Generate crops for this image
        crops = []
        crops = [self.global_crop(img) for _ in range(self.n_global)]
        crops += [self.local_crop(img) for _ in range(self.n_local)]
            
        # Display each crop
        for j, crop in enumerate(crops):
            ax = axs[i, j] if n > 1 else axs[j]
            # Denormalize and convert to display format
            crop_display = self._denormalize(crop).clamp(0, 1)
            crop_display = crop_display.permute(1, 2, 0).cpu().numpy()
            ax.imshow(crop_display)
            ax.axis('off')
            # Add labels for first row
            if i == 0:
                label = 'Global' if j < self.n_global else 'Local'
                ax.set_title(label, fontsize=8)
        
    plt.tight_layout()
    plt.show()

